### ISSUE TITLE
iCloudPD prompting for 2FA code early

### ISSUE THREAD

**Issue by drsparks68** [boredazfcuk/docker-icloudpd#181]
On container startup, it is prompting for a 2FA code, then throws an error.  It's odd because the logs note that there are 20 days left until the 2FA cookie expires. 

![Screenshot 2022-07-11 132730](https://user-images.githubusercontent.com/16406596/178352270-82899ae1-3007-4abe-a647-21372a6951d6.png)
[icloudpd_startup.txt](https://github.com/boredazfcuk/docker-icloudpd/files/9087346/icloudpd_startup.txt)

**Comment by Dids** [comment]
Happens on a daily basis now, if the container is restart/recreated.

**Comment by drsparks68** [comment]
So this is by design even though I have a valid cookie?  I don't see anything in the wiki or recent change logs regarding this.
I'm running this on UnRaid and have a nightly backup job that stops/starts the container; just trying to reduce the number of notifications I'm getting.

**Comment by boredazfcuk** [comment]
My cookie has just expired this morning and I've renewed without issue, using the --Initialise command line switch.

I've also recreated all my containers as I've updated the code. No issues on any of them after recreation either.

This problem looks like an account issue. If you log on to icloud.com, do you get prompted to enter the 2FA details again? Does it say your account is locked and you need to unlock by confirming your security questions? This happens to my Mrs account every few months, for some reason I've not pinpointed. I believe it's probably a brute-force attempt by a malicious actor as she never uses a computer, or accesses her icloud account from anything but her phone.

**Comment by Dids** [comment]
> So this is by design even though I have a valid cookie? I don't see anything in the wiki or recent change logs regarding this. I'm running this on UnRaid and have a nightly backup job that stops/starts the container; just trying to reduce the number of notifications I'm getting.

Can you try completely recreating the container, as well as making sure to pull and run the image with a tag specified?
This fixed it for me, at least as far as I'm aware, but not entirely sure why.

**Comment by Dids** [comment]
Never mind, still getting this every time/morning when it runs.

My best guess is that because I'm running iOS 16, which now has passcode/Face ID protected albums for at least Recently Deleted and Hidden albums, maybe it has something to do with these? Or some other security related change to the APIs?
(or just a side effect from using beta OS's)

**Comment by boredazfcuk** [comment]
The icloudpd app doesn't use an API. It basically emulates logging on to icloud.com and then downloading all the photos from the website. Maybe they have implemented additional website security for iOS 16 users, but I wouldn't have thought that would be a thing.

I do see a similar thing happen fairly frequently on my Mrs' account though... When I log in to icloud.com with her credentials, it tells me that the account is locked and then I have to answer the security questions to unlock it. Once that's done it works fine though.

I don't know what causes it. Sometimes it'll happen two or three times in a month. Sometimes it won't happen for six months. I suspect it's a malicious actor who has scraped her e-mail address/password from a hacked website leak and attempted to log in, but as her password is now different, they are rejected and the account locked.

Try logging into icloud.com and see what happens.

Thanks.

**Comment by boredazfcuk** [comment]
Closing off as it's not had an update since August.
