### ISSUE TITLE
iOS Shared Libraries

### ISSUE THREAD

**Issue by timrettop** [boredazfcuk/docker-icloudpd#239]
Is there any suggestions on how to debug not seeing any SharedSync libraries when using 
```docker exec -it icloudpd-shared /usr/bin/icloudpd --list-libraries```
with the icloudpd:testing docker container? 

I'm looking to try out backing up a shared library to a separate backup location and am only seeing PrimarySync library. 

I use iOS 16 and have shared a new album for testing (and have some that have been around for a while in my icloud library.

**Comment by timrettop** [comment]
Could it be that the PR here would fix that? 
https://github.com/icloud-photos-downloader/icloud_photos_downloader/pull/489

**Comment by boredazfcuk** [comment]
That’s the patch which I merge to enable shared library downloads. Without it, there is no --list-libraries command line option.

**Comment by khargy** [comment]
Not clear from the comments, does the latest version of the docker support Shared Libraries?

**Comment by michaelin1208** [comment]
mark

**Comment by boredazfcuk** [comment]
> Not clear from the comments, does the latest version of the docker support Shared Libraries?

No, the version with the iOS16 shared library patches applied is: boredazfcuk/icloudpd:testing

I ran it for a while on my home server, but it broke after a couple of days. I don't even have shared libraries enabled on my account, so had to roll the code back to the previous version.

**Comment by khargy** [comment]
> > Not clear from the comments, does the latest version of the docker support Shared Libraries?
> 
> No, the version with the iOS16 shared library patches applied is: boredazfcuk/icloudpd:testing
> 
> I ran it for a while on my home server, but it broke after a couple of days. I don't even have shared libraries enabled on my account, so had to roll the code back to the previous version.

Thanks for the reply, I saw your note about the testing repository the other day. So far I haven't had any issues even with downloading from a large shared library.

**Comment by epheterson** [comment]
Did something change? Looks like this was working but stopped. I'm using icloudpd:latest (not testing, but have never used testing).

```
2022-12-12 13:16:30 INFO     iCloudPD launch command: /usr/bin/icloudpd --directory /home/(user)/iCloud --cookie-directory /config --folder-structure {:%Y/%m/%d} --username (email) --auto-delete --library SharedSync-(UUID)  2>/tmp/icloudpd/icloudpd_download_error
2022-12-12 13:16:31 ERROR    Failed to download new files
2022-12-12 13:16:31 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2022-12-12 13:16:31 ERROR    Error debugging info:
2022-12-12 13:16:31 ERROR    Error: no such option: --library
2022-12-12 13:16:31 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
```

**Comment by boredazfcuk** [comment]
> Did something change? Looks like this was working but stopped. I'm using icloudpd:latest (not testing, but have never used testing).

The iOS shared library patches broke basic functionality for a lot of people (myself included):
https://github.com/boredazfcuk/docker-icloudpd/issues/235

So I pulled the patches and added them to the testing container, as it seems that something isn't quite right with them.

**Comment by epheterson** [comment]
Interesting, I have two other personal library containers and both have been working (save one odd issue). I might move my container to testing, or wait for the code to be fixed and pushed back to latest. Thanks for the update!

**Comment by epheterson** [comment]
The odd issue I'm seeing is that some files will be downloaded then deleted on the same run, repeatedly. New files do seem to get added, so haven't really seen an issue with it. This never happened before the shared library changes, so might be related. It's still happening on the current latest tag, though, so maybe something else. Let me know if I should file a unique issue.

e.g.
```
2022-12-12 13:10:27 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
/home/username/iCloud/2021/03/19/IMG_8867.jpeg
2022-12-12 13:21:24 INFO     Downloading /home/username/iCloud/2021/03/19/IMG_8867.jpeg
2022-12-12 13:34:11 INFO     Deleting /home/username/iCloud/2021/03/19/IMG_8867.jpeg!
```

Logs: [iCloudPD-logs.txt](https://github.com/boredazfcuk/docker-icloudpd/files/10212913/iCloudPD-logs.txt)

**Comment by boredazfcuk** [comment]
I get this a lot. Have done for a long while. It's usually because I have saved files from an external app, such as Signal or Telegram, deleted them, and then realised I wanted them back, so saved them again. This means I have two files with the same name. One in Photos and one in recently deleted.

When the script runs, it sees there is a photo in the photo stream named IMG_1234.HEIC (or whatever) and sees it does not exist on the local filesystem, so downloads it. After it finishes downloading, it scans the "Recently Deleted" folder, sees a file in there called IMG_1234.HEIC, sees that it matches a file in the photo stream and so removes it.

I usually just find the matching files in 'Recently Deleted' and remove them permanently.

**Comment by epheterson** [comment]
Thanks, that explains it. I think in my case this is happening because I used the merge duplicates feature in Photos app. 

A simple fix, I think, would be to only delete a file iff it's in recently deleted and the same filename was *not* detected in the original sync / photo stream as a download/existing photo. This is kind of derailing the point of this thread, I can file a new ticket if we think this is worth doing.

**Comment by timrettop** [comment]
Seeing you close this reminded me that I could never get the shared libary UUID to show.  I just tried again using this command with the :testing branch and get an API error, any thoughts: 

/ # icloudpd --list-libraries
iCloud username/email: timapotter@icloud.com
2023-04-10 12:48:09 DEBUG    Authenticating...
iCloud Password: 
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 293, in main
    libraries_dict = icloud.photos.libraries
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 275, in libraries
    libraries[zone_name] = PhotoLibrary(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 154, in __init__
    request = self.service.session.post(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: INTERNAL_ERROR (INTERNAL_ERROR)

**Comment by timrettop** [comment]
Ahh, the same error was found and reported in the upstream PR that was never merged. 
https://github.com/icloud-photos-downloader/pyicloud/pull/8#issuecomment-1453072803

**Comment by boredazfcuk** [comment]
The upstream project seemed like it had stalled for a while, but then a flood of updates came in January/February... It's what kind of got me re-interested in the project (as well as increased personal time to work on it).

It's slowed down somewhat over the past month, but hopefully they're still working on it.

**Comment by jcbshw** [comment]
FYI looks like Shared Library is working now. I never had success with the testing container previously but after seeing recent success in https://github.com/icloud-photos-downloader/pyicloud/pull/8 I have it another try.

Only issue I encountered is needing to run "chmod 750 /iCloud" to fix permissions but that's unrelated to Shared Library support.

**Comment by boredazfcuk** [comment]
That is the original PR which I merged into the testing container. It won't work on the latest version of the container as it's based on old code. If the PR gets rebased and merged upstream, I'll update the version bundled in the container and re-enable the functions. Until that happens though, the functionality will just have to stay in the testing container.

I will re-open this as a reminder though.

**Comment by tangyue1** [comment]
I would love to see the upstream code works with shared library. I noticed that only my personal library is being downlaoded now.

**Comment by laurensguijt** [comment]
Is there any progress with the shared librarys? I would love to use this for a specific shared library.

**Comment by lonevvolf** [comment]
Looks like there actually is - check here:
https://github.com/icloud-photos-downloader/icloud_photos_downloader/pull/678

**Comment by tangyue1** [comment]
Really appreciate the hard work you put in. would like to see this feature added. For once it worked with the testing image but some update broke it.

**Comment by epheterson** [comment]
Somehow testing image is still working for me 🤷‍♂️ Also appreciate all the hard work and look forward to support in the main image someday!

**Comment by jcbshw** [comment]
Shared Library support was just merged upstream

https://github.com/icloud-photos-downloader/icloud_photos_downloader/pull/678

**Comment by boredazfcuk** [comment]
I've re-enabled the code which should support shared libraries again. I don't actually have any to test with though, so feedback would be appreciated.

**Comment by timrettop** [comment]
Looks like they're testing the bug in your link above, I get the same outcome with your latest update.  I guess if they rev the version with a fix, you'll have to do the same?

**Comment by boredazfcuk** [comment]
Yeah, once they've pushed a fixed version, I'll just rebuild mine again.

Thought I'd push the current code out so that people using my container can report their findings. With more users testing, it will help ascertain whether the issue is widespread or only affecting a small number of users.

**Comment by jcbshw** [comment]
I can confirm downloading my shared library with the updated container is working.

I did not test --list-libraries since I already had my shared library name.

**Comment by theskyisthelimit** [comment]
I was looking forward for this feature. I tried running the --list-libraries but get the following message:

```
/ # sync-icloud.sh --list-libraries

2023-09-27 07:17:15 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.635 started *****
2023-09-27 07:17:15 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-09-27 07:17:15 INFO     Alpine Linux 3.18.3
2023-09-27 07:17:15 INFO     Python version: 3.11.5
2023-09-27 07:17:15 INFO     Loading configuration from: /config/icloudpd.conf
2023-09-27 07:17:18 INFO     Apple ID: XXXX
2023-09-27 07:17:18 INFO     Authentication Type: MFA
2023-09-27 07:17:18 INFO     Cookie path: /config/XXXX
2023-09-27 07:17:18 INFO     Cookie expiry notification period: 7
2023-09-27 07:17:18 INFO     Download destination directory: /home/user/iCloud
2023-09-27 07:17:18 INFO     Folder structure: {:%Y/%m/%d}
2023-09-27 07:17:18 INFO     Synchronisation interval: 86400
2023-09-27 07:17:18 INFO     Synchronisation delay (minutes): 0
2023-09-27 07:17:18 INFO     Set EXIF date/time: false
2023-09-27 07:17:18 INFO     Auto delete: false
2023-09-27 07:17:18 INFO     Delete after download: false
2023-09-27 07:17:18 INFO     Photo size: original
2023-09-27 07:17:18 INFO     Single pass mode: false
2023-09-27 07:17:18 INFO     Skip download check: false
2023-09-27 07:17:18 INFO     Skip live photos: false
2023-09-27 07:17:18 INFO     Number of most recently added photos to download: Download All Photos
2023-09-27 07:17:18 INFO     Downloading photos from album: Download All Photos
2023-09-27 07:17:18 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-09-27 07:17:18 INFO     Live photo size: original
2023-09-27 07:17:18 INFO     Skip videos: false
2023-09-27 07:17:18 INFO     Convert HEIC to JPEG: false
2023-09-27 07:17:18 INFO     Downloading from: icloud.com
2023-09-27 07:17:18 INFO     Authentication domain: com
2023-09-27 07:17:18 INFO     Ignore Synology extended attribute directories: Disabled
2023-09-27 07:17:18 WARNING  Ignoring invalid launch parameter specified: --list-libraries
2023-09-27 07:17:18 WARNING  Please do not specify the above parameter when launching the container. Continuing in 2 minutes
```

Am I doing something wrong?

**Comment by ryan-adler** [comment]
Same issue here - I'm also seeing #237 when trying to do a normal sync.

**Comment by lonevvolf** [comment]
Could it be that the --list-albums and --list-libraries params are missing here?
https://github.com/boredazfcuk/docker-icloudpd/blob/60997762aa2fc5dba5022f066d2bb319706d8d8d/sync-icloud.sh#L1916

**Comment by boredazfcuk** [comment]
> Could it be that the --list-albums and --list-libraries params are missing here?
> 
> https://github.com/boredazfcuk/docker-icloudpd/blob/60997762aa2fc5dba5022f066d2bb319706d8d8d/sync-icloud.sh#L1916

Yeah... I thought I'd just commented out all the stuff for shared libraries when I disabled it. Looks like I removed the command line parameter for that, and also for --photo-album too.

Both have been re-enabled. Codebase has moved to 1.16.1 too, so it will have the fix in it, which causes an error in certain circumstances.

**Comment by theskyisthelimit** [comment]
One step further but the script stops without listing the libraries.

```
2023-09-28 06:51:58 INFO     Directory is writable: /config/python_keyring/
2023-09-28 06:51:58 INFO     Directory is writable: /home/user/.local/share/
2023-09-28 06:51:58 INFO     Shared libraries available:
2023-09-28 06:51:59 DEBUG    Authenticating...
2023-09-28 06:52:03 INFO     Albums available:
2023-09-28 06:52:03 INFO      - PrimarySync
/ # 
```

**Comment by timrettop** [comment]
It works for me! 🕺   Thank you!!!

@theskyisthelimit you might not have setup a shared library. I got confused with shared albums and shared library.  

Check in your iOS Settings -> Photos and see if you've setup a Shared Album.

**Comment by theskyisthelimit** [comment]
> It works for me! 🕺 Thank you!!!
> 
> @theskyisthelimit you might not have setup a shared library. I got confused with shared albums and shared library.
> 
> Check in your iOS Settings -> Photos and see if you've setup a Shared Album.

I have set up shared libraries.

**Comment by boredazfcuk** [comment]
> It works for me! 🕺 Thank you!!!

I'm not sure how. I've looked at the code and could not see anywhere that a shared library would be downloaded. Yes, it had the capability to list the libraries by name and to list/download albums, but I couldn't see anywhere it would actually download the library.

I've had to give it quite a major reworking... basically copy/pasted a chunk of about 30 lines of code that downloads albums and convert it to run against libraries instead.

Hopefully it should work now. @theskyisthelimit can you pull the latest version and see what happens?

**Comment by theskyisthelimit** [comment]
> Hopefully it should work now. @theskyisthelimit can you pull the latest version and see what happens?

@boredazfcuk , Much appreciated! Unfortunately, the behavior is still the same:

excerpt from the log: 

```
2023-09-28 23:15:20 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.643 started *****
.......
.......
2023-09-28 23:15:22 INFO     Shared libraries available:
2023-09-28 23:15:24 DEBUG    Authenticating...
2023-09-28 23:15:28 INFO     Libraries available:
2023-09-28 23:15:28 INFO      - PrimarySync
```

**Comment by boredazfcuk** [comment]
It is returning the name of a shared library though: PrimarySync

Have you tried setting `photo_libary=PrimarySync` and checked what it does/downloads?

**Comment by fver** [comment]
Looking into this, it seems to be you only get access to the shared library from the account that owns it, not from the account that receive the share.
Can you try a list-library with the email and passwd from the owner of the share?

**Comment by lonevvolf** [comment]
The version that was current this morning is working for me - currently downloading my huge library since this morning.  Seems to be some major confusion here...

**Comment by boredazfcuk** [comment]
I've found the bit that did the downloading on the version earlier today:
```
   if [ -z "${photo_album}" ] && [ "${photo_library}" ]; then
      command_line="${command_line} --folder-structure ${folder_structure}"
   fi
   if [ "${photo_album}" ]; then
      command_line="${command_line} --album ${photo_album}"
   elif [ "${photo_library}" ]; then
      command_line="${command_line} --library ${photo_library}"
   fi
```
I think this bit was a typo `[ -z "${photo_album}" ] && [ "${photo_library}" ]` and should have been `[ -z "${photo_album}" ] && [ -z "${photo_library}" ]`. That way, if neither an album or library is configured, it falls back to using the folder structure.

The following bit then adds the library to download to the command line:
```
   if [ "${photo_album}" ]; then
      command_line="${command_line} --album ${photo_album}"
   elif [ "${photo_library}" ]; then
      command_line="${command_line} --library ${photo_library}"
   fi
```
So that's where it was. I've tidied all that up now, so hopefully should be cleaner.

**Comment by theskyisthelimit** [comment]
> It is returning the name of a shared library though: PrimarySync
> 
> Have you tried setting `photo_libary=PrimarySync` and checked what it does/downloads?

Tried it now but nothing "more" happens. My "primary" library, not the shared one is working fine. Im also the owner of the shared library. 

I would expect to have 2 libraries here with the command --list-libraries

```
2023-09-28 23:15:28 INFO     Libraries available:
2023-09-28 23:15:28 INFO      - PrimarySync
???
```

**Comment by theskyisthelimit** [comment]
I let it run for a while and it created a new folder called PrimarySync in the same folder as the yearly folders are and downloaded all images from my primary library. But still nothing from the shared library. Is there like a default name for the shared library?

**Comment by tangyue1** [comment]
The latest image downloads the shared folder but did not respect the folder_structure option. It downloads into a flat folder called "SharedSync-xxx"

**Comment by theskyisthelimit** [comment]
`# sync-icloud.sh --list-libraries` still not listing the shared library.

```
2023-10-01 05:53:26 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.649 started *****
........
2023-10-01 05:53:38 INFO     Shared libraries available:
2023-10-01 05:53:38 INFO      - PrimarySync
/ # 
```

anything else I could try?

**Comment by KUMAKAIHA** [comment]
> sync-icloud.sh --list-libraries

I also have the same problem. Only PrimarySync is displayed, and if `photo_libary=PrimarySync` is used, a PrimarySync folder will be generated, and unordered photos that are not in the shared gallery will be synchronized to this folder

**Comment by yieldhog** [comment]
> The latest image downloads the shared folder but did not respect the folder_structure option. It downloads into a flat folder called "SharedSync-xxx"

I have the same issue -- Additionally, when I set the configuration "photo_library" to SharedSync-XXX it quit downloading my original non-shared library. When I set the variable to "all albums" I get the following error in logs:

---
2023-10-01 09:03:36 INFO     Check successful
2023-10-01 09:03:36 INFO     New files detected: 62
2023-10-01 09:03:38 INFO     Downloading library: all albums
Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: Got unexpected extra arguments (albums albums albums)
---
Anyone find a solution to this?

**Comment by boredazfcuk** [comment]
> Downloading library: all albums

Albums and Libraries are different concepts as far as iCloud is concerned. Attempting to download from a shared library named "all albums" doesn't wound like something that should work.

**Comment by yieldhog** [comment]
> > Downloading library: all albums
> 
> Albums and Libraries are different concepts as far as iCloud is concerned. Attempting to download from a shared library named "all albums" doesn't sound like something that should work.

I suppose that's true -- should probably update the configuration.

**photo_library:** Set this to a comma delimited field to download photos from a shared library. Please note, if downloading from multiple libraries, you need to enclose them in quotes in your /config/icloudpd.conf file e.g. photo_library="one,two,three and four" will download photos from three libraries named "one", "two" and "three and four". When downloading photo libraries, the folder structure will be set to be the name of the library eg "/home/boredazfcuk/iCloud/one/IMG_0001.HEIC", "/home/boredazfcuk/iCloud/two/IMG_0002.HEIC" and "/home/boredazfcuk/iCloud/three and four/IMG_0003.HEIC". **Set photo_library="all albums" in your configuration file /config/icloudpd.conf to download all albums.** Please note: Due to a limitation in an upstream package, downloading from multiple libraries will trigger multiple download runs, and Apple may force a multi-factor re-authentication.

**Comment by KUMAKAIHA** [comment]
I think we need a quick solution to synchronize shared library photos from iOS16. Because once your photos are marked as a shared library, whether from yourself or others, they will not be synchronized to NAS in the existing version as usual.
It is now known that using `photo_library="all albums"` will result in errors, and using `photo_libary=PrimarySync` will not result in the correct synchronization library

**Comment by jcbshw** [comment]
I think I figured it out. It looks like "sed '1d'" is cutting off the shared library name.

https://github.com/boredazfcuk/docker-icloudpd/blob/a5eda0f74f74d5ea9abe81e2b7b7d1f32d743e83/sync-icloud.sh#L697

Running the command manually inside the container without sed provides the shared library name.

libraries_with_dates is also commented out in sync-icloud.sh preventing folder structure to be followed 

https://github.com/boredazfcuk/docker-icloudpd/blob/a5eda0f74f74d5ea9abe81e2b7b7d1f32d743e83/sync-icloud.sh#L33

**Comment by boredazfcuk** [comment]
> > > Downloading library: all albums
> > 
> > 
> > Albums and Libraries are different concepts as far as iCloud is concerned. Attempting to download from a shared library named "all albums" doesn't sound like something that should work.
> 
> I suppose that's true -- should probably update the configuration documentation.
> 
> **photo_library:** Set this to a comma delimited field to download photos from a shared library. Please note, if downloading from multiple libraries, you need to enclose them in quotes in your /config/icloudpd.conf file e.g. photo_library="one,two,three and four" will download photos from three libraries named "one", "two" and "three and four". When downloading photo libraries, the folder structure will be set to be the name of the library eg "/home/boredazfcuk/iCloud/one/IMG_0001.HEIC", "/home/boredazfcuk/iCloud/two/IMG_0002.HEIC" and "/home/boredazfcuk/iCloud/three and four/IMG_0003.HEIC". **Set photo_library="all albums" in your configuration file /config/icloudpd.conf to download all albums.** Please note: Due to a limitation in an upstream package, downloading from multiple libraries will trigger multiple download runs, and Apple may force a multi-factor re-authentication.

I just copy/pasted that text and changed the word album to library; looks like I missed a couple. I've not actually commissioned the multiple libraries stuff either yet, which is why some lines of code are commented out. I don't use shared libraries so I've no idea how they work, how they're named (as far as the system is concerned). etc.

**Comment by boredazfcuk** [comment]
> I think I figured it out. It looks like "sed '1d'" is cutting off the shared library name.
`1d` deletes the first line of text, which look like this:
```
2023-10-02 19:21:20 DEBUG    Authenticating...
```

> Running the command manually inside the container without sed provides the shared library name.

When I run it inside the container without the sed command, I get:
```
/ # /opt/icloudpd_latest/bin/icloudpd --username blah@email.com --cookie-directory ${config_dir} --domain com --directory /dev/null --list-libraries
2023-10-02 20:11:54 DEBUG    Authenticating...
PrimarySync
```
which is to be expected, as I don't use libraries. Running it with sed produces the library list:
```
/ # /opt/icloudpd_latest/bin/icloudpd --username blah@e-mail.com --cookie-directory ${config_dir} --domain com --directory /dev/null --list-libraries | sed '1d'
PrimarySync
```

> 
> libraries_with_dates is also commented out in sync-icloud.sh preventing folder structure to be followed

I've not implemented this yet. I don't use shared libraries, so wasn't sure if multiple shared libraries was a thing, which is why it was commented out.

**Comment by jcbshw** [comment]
This is what happens for myself:

```
/ # /opt/icloudpd_latest/bin/icloudpd --username example@example.com --cookie-directory ${config_dir} --domain com --directory /dev/null --list-libraries
SharedSync-########-####-####-####-############
PrimarySync
```
```
/ # /opt/icloudpd_latest/bin/icloudpd --username example@example.com  --cookie-directory ${config_dir} --domain com --directory /dev/null --list-libraries | sed '1d'
PrimarySync
```
<br></br>
> > libraries_with_dates is also commented out in sync-icloud.sh preventing folder structure to be followed
> 
> I've not implemented this yet. I don't use shared libraries, so wasn't sure if multiple shared libraries was a thing, which is why it was commented out.

Users with shared libraries would just have PrimarySync and SharedSync. It would be nice to have that uncommented so we can have the folder structure followed for the shared library.

**Comment by theskyisthelimit** [comment]
I just ran `# sync-icloud.sh --list-libraries | sed '1d'` inside the docker container and I also obtained the SharedSync Library Name in the same format SharedSync-########-####-####-####-############

**Comment by theskyisthelimit** [comment]
I am able to download the shared library when adding it to the config like this:

`photo_library=SharedSync-########-####-####-####-############`

It then downloads the files into a seperate folder without the structure.

Tomorrow I will try both libraries, comma seperated in the config. Then the last thing missing would be (maybe as an option) to have all files from both libraries in the same folder structure (folder_structure={:%Y/%m/%d}).

**Comment by boredazfcuk** [comment]
> This is what happens for myself:
> 
> ```
> / # /opt/icloudpd_latest/bin/icloudpd --username example@example.com --cookie-directory ${config_dir} --domain com --directory /dev/null --list-libraries
> 2023-10-02 12:22:54 DEBUG    Authenticating...
> SharedSync-########-####-####-####-############
> PrimarySync
> ```
> 
> ```
> / # /opt/icloudpd_latest/bin/icloudpd --username example@example.com  --cookie-directory ${config_dir} --domain com --directory /dev/null --list-libraries | sed '1d'
> 2023-10-02 12:28:47 DEBUG    Authenticating...
> PrimarySync
> ```
> 
> > > libraries_with_dates is also commented out in sync-icloud.sh preventing folder structure to be followed
> > 
> > 
> > I've not implemented this yet. I don't use shared libraries, so wasn't sure if multiple shared libraries was a thing, which is why it was commented out.
> 
> Users with shared libraries would just have PrimarySync and SharedSync. It would be nice to have that uncommented so we can have the folder structure followed for the shared library.

Are you running an older version of the container? There was an upstream change which pushed info out to stderr instead of stdout. That could be what's happening... The DEBUG line may be getting pushed to stderr, so displayed in console, but ignored by sed.

I've pushed a new version which enables the configuration items for shared libraries with folder structure. Please test and let me know.

**Comment by boredazfcuk** [comment]
> Tomorrow I will try both libraries, comma seperated in the config. Then the last thing missing would be (maybe as an option) to have all files from both libraries in the same folder structure (folder_structure={:%Y/%m/%d}).

Folder structure wasn't implemented for Shared Libraries. It is in the version I've just pushed now though.

**Comment by tangyue1** [comment]
I set the photo_library=SharedSync-xxx and folder structure is still not respected in the latest image. Can it NOT add the SharedSync-xxx folder and just create folder structure under the set volume?

**Comment by boredazfcuk** [comment]
>Can it NOT add the SharedSync-xxx folder and just create folder structure under the set volume?

No, people wanting to download from multiple shared libraries would have their libraries merged.

If you want to have libraries with dates, you need to set `libraries_with_dates=true`, same as how downloading from photo albums is handled.

**Comment by tangyue1** [comment]
libraries_with_dates=True, photo_library=SharedSync-xxx, Stop condition is either until_found=100 or recent_only=100 The latest image won't download any photo. 
2023-10-04 09:22:22 2023-10-04 09:22:22 INFO     Downloading library: SharedSync-xxx
2023-10-04 09:23:50 2023-10-04 09:23:50 INFO     Synchronisation complete for user

**Comment by boredazfcuk** [comment]
If you remove the stop conditions, does work?

I'm wondering if the new code to download the photos doesn't consider these settings.

**Comment by tangyue1** [comment]
> If you remove the stop conditions, does work?
> 
> I'm wondering if the new code to download the photos doesn't consider these settings.

I removed the stop condition but it still does not download. Here is the debugging, "--library" seems to be invoked twice.

2023-10-04 17:45:11 2023-10-04 17:45:11 INFO     Downloading library: SharedSync-xxx
2023-10-04 17:45:11 2023-10-04 17:45:11 DEBUG    iCloudPD launch command: /opt/icloudpd_latest/bin/icloudpd --directory /home/user/iCloud --cookie-directory /config --domain com --username xxx --no-progress-bar --library SharedSync-xxx --folder-structure SharedSync-xxx/{:%Y/%Y-%m/%Y-%m-%d} --library SharedSync-xxx 2>/tmp/icloudpd/icloudpd_download_error
2023-10-04 17:45:11 2023-10-04 17:45:11 DEBUG    Set owner on iCloud directory, if required
2023-10-04 17:45:31 2023-10-04 17:45:31 DEBUG    Set group on iCloud directory, if required
2023-10-04 17:45:50 2023-10-04 17:45:50 DEBUG    Set 750 permissions on iCloud directories, if required
2023-10-04 17:46:09 2023-10-04 17:46:09 DEBUG    Set 640 permissions on iCloud files, if required
2023-10-04 17:46:28 2023-10-04 17:46:28 INFO     Synchronisation complete for user

**Comment by boredazfcuk** [comment]
Can you update to latest version and test please?

**Comment by tangyue1** [comment]
It is working now. Listing individual libraries like "PrimarySync,SharedSync-########-####-####-####-############" works. But photo_library="all libraries" does not work.

**Comment by lonevvolf** [comment]
I am also not seeing the correct folder structure under the SharedSync-### folder in the newest image.  It's still flat for me.

**Comment by boredazfcuk** [comment]
> I am also not seeing the correct folder structure under the SharedSync-### folder in the newest image.  It's still flat for me.

Did you configure it to download to a dated file structure?

**Comment by lonevvolf** [comment]
`folder_structure={:%Y/%m/%d}`

**Comment by boredazfcuk** [comment]
> `folder_structure={:%Y/%m/%d}`

So no then? `folder_structure` is ignored by photo/library downloads, in favour of named folders, unless confgured otherwise.

**Comment by lonevvolf** [comment]
I guess I'm confused - the doc says that setting that value, or leaving it blank will download files into the date structure.  How can I configure it to use the date structure then?

**Comment by yieldhog** [comment]
Am I having the same issue? I've been using this for about a year or so .. all of my files were downloaded neatly into the default date folders: ie 2023 // 09 // 25

I added the following ENV to my docker container: photo_library: "PrimarySync,SharedSync-ECEXXX"

overnight, it redownloaded all of my 52,000 pictures into a new subfolder "PrimarySync" with no folder structure. What is the best option here? Thanks

**Comment by KUMAKAIHA** [comment]
> > Can it NOT add the SharedSync-xxx folder and just create folder structure under the set volume?
> 
> No, people wanting to download from multiple shared libraries would have their libraries merged.
> 
> If you want to have libraries with dates, you need to set `libraries_with_dates=true`, same as how downloading from photo albums is handled.

When I use 'libraries_with_dates=true' in Docker settings, whether I use Ture or true, it will still be set to false in the icloudpd.conf file

**Comment by KUMAKAIHA** [comment]
> > > Can it NOT add the SharedSync-xxx folder and just create folder structure under the set volume?
> > 
> > 
> > No, people wanting to download from multiple shared libraries would have their libraries merged.
> > If you want to have libraries with dates, you need to set , same as how downloading from photo albums is handled.`libraries_with_dates=true`
> 
> When I use 'libraries_with_dates=true' in Docker settings, whether I use Ture or true, it will still be set to false in the icloudpd.conf file

In Docker version 1.0.665. Once  `photo_library` is used, as `libraries_with_dates` cannot be set to true, photos will not be synchronized according to the file structure of the date. Meanwhile, due to the invalid setting of `photo_library="all libraries"`, only `photo_library= "PrimarySync,SharedSync-XXX"` is allowed to synchronize personal libraries simultaneously. And due to the use of `libraries_with_dates=false`, the personal library will not be able to expand according to the date structure.
Currently, once synchronization of shared libraries begins, it will result in personal libraries being unable to be synchronized or being synchronized in the PrimarySync folder without expanding by date.

**Comment by boredazfcuk** [comment]
Maybe... I think it's not working because of the typo when it generates the conf file, it's something like: libraries_with_datess

I spotted it this morning but not near a computer for a while.

**Comment by KUMAKAIHA** [comment]
> Maybe... I think it's not working because of the typo when it generates the conf file, it's something like: libraries_with_datess
> 
> I spotted it this morning but not near a computer for a while.

Like this ?
`# if [ "${libraries_with_dates}" ]; then sed -i "s%^librariess_with_dates=.*%librariess_with_dates=${librariess_with_dates}%" "${config_file}"; fi`

**Comment by boredazfcuk** [comment]
Yeah that's it. Turns out I've got the coronavirus, so just trying to sleep through the worst of it. Maybe pick this up in a few days as I don't have my laptop to alter the code.


If any of you guys want to submit a PR with the change I can approve it and kick off the build/deployment from my phone. Otherwise you're just gonna have to wait a few days till I'm good again.

**Comment by KUMAKAIHA** [comment]
> Yeah that's it. Turns out I've got the coronavirus, so just trying to sleep through the worst of it. Maybe pick this up in a few days as I don't have my laptop to alter the code.
> 
> If any of you guys want to submit a PR with the change I can approve it and kick off the build/deployment from my phone. Otherwise you're just gonna have to wait a few days till I'm good again.

Wishing you a speedy recovery. I don't know much about GitHub and Docker, but I deleted the extra s in line 108 'librariess_with_dates' and submitted a PR

**Comment by boredazfcuk** [comment]
Definitely on the mend, feeling loads better in last few hours. Should be back to normal by tomorrow.

**Comment by boredazfcuk** [comment]
I've pushed another update today. I found a bug in how albums are processed and made quite a few changes to that.

The Libraries functionality was basically a copy/paste job, so a few of these bugs were in there too. Hopefully it should work a little better now.

**Comment by jmmartos** [comment]
Hi Boredazfcuk, first of all thank you for your great work!

My question is about synchronisation when using a shared library, is there a way to make it download both libraries in one folder instead of using separate folders?

Under photos folder I have right now this structure:

|── PrimarySync
│   ├── 2020
│   ├── 2021
│   ├── 2022
│   └── 2023
|── SharedSync-XXXX-XXX-XXXX-XXX-XXXXXX
│   ├── 2020
│   ├── 2021
│   ├── 2022
│   └── 2023


I would like it to look like this:

|── Photos
│   ├── 2020
│   ├── 2021
│   ├── 2022
│   └── 2023

Is there any possibility to merge the two folders into one?

Thanks in advance.

**Comment by boredazfcuk** [comment]
Hi,

Personally, I don't download from Photo Libraries, so I've no experience of how they behave... but I think you may run into issues attempting to merge the libraries like that.

I'd imagine it's entirely possible that two different photos exist in each library, but use the same name IMG_0000.HEIC, for example. 

After the first file is downloaded from the PrimarySync, the second file from SharedSync will be de-duplicated, so named something like IMG_0000-12345.HEIC.

After this, say you decided to delete IMG_0000.HEIC from the SharedSync library, the app finds IMG_0000.HEIC in deleted items. It has no way of knowing which Library that file came from, so it would delete the file on disk named IMG_0000.HEIC, which would be the file from PrimarySync.

**Comment by boredazfcuk** [comment]
Resolved long ago... just doing some long overdue housekeeping.
