### ISSUE TITLE
Upon each container initiation, a WeCom notification is dispatched, but no subsequent notifications ensue

### ISSUE THREAD

**Issue by lhlxx2010** [boredazfcuk/docker-icloudpd#341]
Upon each container initiation, a WeCom notification is dispatched, but no subsequent notifications ensue. I have verified the accuracy of all parameters, as otherwise, notifications would not be sent at startup.

Below are the detailed logs; I am uncertain about the origin of the WeCom token. It appears there is no designated location to input this information.

2023-05-26 23:58:32 INFO     All photos have been downloaded!
2023-05-26 23:58:32 INFO     New files downloaded: 86
2023-05-26 23:58:32 INFO     Sending WeCom downloaded files notification
2023-05-26 23:58:32 WARNING  WeCom token has expired. Retrieving new one
2023-05-26 23:58:33 INFO     WeCom token: edxaFI39Vi675CyAyJi8nd6WcWS7*********************************************************W6HZa9XqsOk1ZD7-zngcDWjpHaxtJ3l5rTyyGIaCVA
2023-05-26 23:58:33 INFO     WeCom token expiry time: Sat May 27 01:58:33 CST 2023
2023-05-26 23:58:33 INFO     WeCom notification URL: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=edxaFI39Vi675CyAyJi8nd6WcWS7*********************************************************jpHaxtJ3l5rTyyGIaCVA
2023-05-26 23:59:12 INFO     Synchronisation complete for user
2023-05-26 23:59:12 INFO     Web cookie expires: 2023-07-07 @ 13:42:21
2023-05-26 23:59:12 INFO     Two factor authentication cookie expires: 2023-08-06 @ 13:42:31
2023-05-26 23:59:12 INFO     Days remaining until expiration: 71
2023-05-26 23:59:12 INFO     Synchronisation ended at 23:59:12
2023-05-26 23:59:12 INFO     Total time taken: 00:22:02
2023-05-26 23:59:12 INFO     Next synchronisation at 23:37:10

**Comment by boredazfcuk** [comment]
@Alano-i Doy ou also see this behaviour?

**Comment by Alano-i** [comment]
I seem to be running normally here.

you can check whether all wecom parameters are set. 

Post your environment variables and icloudpd.conf file and we can see what the problem is.

**Comment by boredazfcuk** [comment]
Thanks for the confirmation.

**Comment by lhlxx2010** [comment]
> I seem to be running normally here.
> 
> you can check whether all wecom parameters are set.
> 
> Post your environment variables and icloudpd.conf file and we can see what the problem is.

Can you help take a look? I think there is no problem with the settings, as notifications are sent normally the first time the container is started.
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/c9042f78-15b2-423a-b406-2362951cb678)
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/5281cf08-64e0-4476-9b02-00ce37a3d7cc)

**Comment by boredazfcuk** [comment]
I've pushed a new version which does not sanitise the **notification_title** value for WeCom notifications. I'm wondering if it is something to do with that as there is another person reporting a problem with it. Please upgrade to the latest version and test again.

**Comment by lhlxx2010** [comment]
> I've pushed a new version which does not sanitise the **notification_title** value for WeCom notifications. I'm wondering if it is something to do with that as there is another person reporting a problem with it. Please upgrade to the latest version and test again.

I have updated to the latest version, but it seems that the issue remains unresolved. Similarly, although I receive Enterprise WeChat notifications when the container is first started, I still do not receive any notification after downloading the photos. Below is the log at the end for your reference. Thank you for your attention.
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/91f474b8-269c-4859-b125-f7bdf32f52cb)

**Comment by lhlxx2010** [comment]
> I've pushed a new version which does not sanitise the **notification_title** value for WeCom notifications. I'm wondering if it is something to do with that as there is another person reporting a problem with it. Please upgrade to the latest version and test again.

Last evening, the process ran automatically once more (set to loop every 48 hours), with the log snapshot as follows; it commenced and concluded without any notifications.

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/7167bcd6-767f-429c-851c-903e7dd3e38e)

**Comment by boredazfcuk** [comment]
OK, so something really weird is happening here. It seems it's getting to the part where is attempts to send the message, but then breaking out of the function before getting to the end where it reports the success/failure of sending the message.

Your log should look more like this:
```
WeCom Notification URL: xxxx
WeCom downloaded files notification successful/failed
Synchronisation complete for user
```

I've created a new version with a little more logging around this area. Can you please update and send an updated log file?

**Comment by lhlxx2010** [comment]
> OK, so something really weird is happening here. It seems it's getting to the part where is attempts to send the message, but then breaking out of the function before getting to the end where it reports the success/failure of sending the message.
> 
> Your log should look more like this, but it's missing the middle line:
> 
> ```
> WeCom notification URL: xxxx
> WeCom downloaded files notification successful/failed
> Synchronisation complete for user
> ```
> 
> I've created a new version with a little more logging around this area. Can you please update and send an updated log file?

thank you sooo much！I will update the new version today!

**Comment by lhlxx2010** [comment]
> OK, so something really weird is happening here. It seems it's getting to the part where is attempts to send the message, but then breaking out of the function before getting to the end where it reports the success/failure of sending the message.
> 
> Your log should look more like this, but it's missing the middle line:
> 
> ```
> WeCom notification URL: xxxx
> WeCom downloaded files notification successful/failed
> Synchronisation complete for user
> ```
> 
> I've created a new version with a little more logging around this area. Can you please update and send an updated log file?

This marks my inaugural initiation of a Docker container, notification proceeded without abnormalities, followed by the subsequent log snapshot as presented.
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/bc92ae49-d6f9-446e-b405-16eed8eedbbc)

The photographic contents have now reached the culmination of their download process, with the log ensuing as mentioned below.
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/79a80343-f6d7-42dd-b237-ca04734a7fa3)

**Comment by boredazfcuk** [comment]
I've pushed another version. The one I previously pushed would only display the log entries if debug logging was enabled.

Please update again and post another log.

**Comment by lhlxx2010** [comment]
> I've pushed another version. The one I previously pushed would only display the log entries if debug logging was enabled.
> 
> Please update again and post another log.

The outcomes mirror each other, as visualised in the snapshot. Curiously, 'result' consistently displays '200'. While the preliminary notification intimating the initiation of the container seemingly transmitted successfully, the subsequent completion of synchronization, despite log affirmations of successful dispatch, was paradoxically not received. The root cause remains elusive…

![d26dd212a5eda6a7bb9656fc015ee5b](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/0dabdc4a-15fc-4768-be61-f6407a51735e)


![380e615c278e63640ed6ce04eb13cbf](https://github.com/boredazfcuk/docker-icloudpd/assets/74414383/01f7792d-55f1-4006-86aa-a295905d6a23)

**Comment by boredazfcuk** [comment]
Closing this off as we've been unable to reproduce the issue.
