### ISSUE TITLE
Error: Invalid value for '--keep-unicode-in-filenames': '--live-photo-mov-filename-policy' is not a valid boolean.

### ISSUE THREAD

**Issue by myzonexx** [boredazfcuk/docker-icloudpd#586]
after update to latest version, I restart the container to sync again and it shows the following error
Error: Invalid value for '--keep-unicode-in-filenames': '--live-photo-mov-filename-policy' is not a valid boolean.
I also tried to add this 2 value into configuration files but it didn't work.
anyone knows how to fix it?

**Comment by yieldhog** [comment]
I'm having the same issue, files are no longer downloading

**Comment by boredazfcuk** [comment]
What does your configuration file say for those two options?

**Comment by yieldhog** [comment]
I upgraded container from a prior version, there are no entries in the icloudpd.conf file for me related to these options

**Comment by meserwinowski** [comment]
+1 to this issue, same symptoms, just updated docker image and running to this on container start. 
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/17987360/b3124a4b-9b0c-4ef4-ba55-2e6ce4912b26)

**Comment by imagesafari** [comment]
Also just pulled a new image and am getting this same error. +1

**Comment by JuliusB1601** [comment]
I had the same error. After adding these two to the config with the defaults mentioned in the Configuration.md, everything works fine.

**Comment by boredazfcuk** [comment]
The script adds the defaults for these settings at launch if it doesn't find them in the icloudpd.conf file already. If they are not there, then there's likely a permissions issue writing to the file.

**Comment by boredazfcuk** [comment]
I run four separate containers, and have added around a dozen options to the config file, since the initial code to create it. I've never seen it fail in testing so in the region of 50ish successful tests.

**Comment by boredazfcuk** [comment]
> This is a correct suggestion. 
> I tried to add those missing config and fill in the default values, it works fine. 
> Previously I thought I just remain blank after =, it will use default value but actually not.

It does not fix the root cause. As further options are added to the icloupd.conf file, these will also fail to be added to the config file.

**Comment by yieldhog** [comment]
Perhaps I'm missing something here, but, I've pulled down a new image and the new options do not show up in the conf file. There are no permission issues, do I need to delete the container and rebuild from scratch?

**Comment by boredazfcuk** [comment]
> This is a correct suggestion. I tried to add those missing config and fill in the default values, it works fine. Previously I thought I just remain blank after =, it will use default value but actually not.

I've pushed a new version which may resolve this. The script now checks a bunch of variables, and sets a default value for them, if it finds that they are blank.

The script should have added the variables and set their default value. I'm not sure how yours managed to create the setting, but not populate it with the default value. Anyway, that should be fixed in the latest version.

**Comment by lonevvolf** [comment]
Still having the same issue - have to add them to config with values set
