### ISSUE TITLE
Add support for multiple sizes

### ISSUE THREAD

**Issue by jmalexan** [boredazfcuk/docker-icloudpd#606]
In 1.19.0, icloudpd added support for supplying multiple sizes to download, see [here](https://icloud-photos-downloader.github.io/icloud_photos_downloader/size.html).

In particular this can be used if a photo has both a RAW version and a JPEG version, to download both versions at once by specifying "--size original --size alternative".  An "adjusted" size is also available to download edited versions of photos as well.  I'd like to use these, but as far as I can see the config file doesn't support supplying multiple values to this specific argument.

I briefly looked into the CLI argument library icloudpd is using, and it looks like supplying a comma separated list is not a valid way to supply multiple values to this particular argument (e.g. it must be "--size original --size alternative", not "--size original, alternative".  However, maybe this project could accept such comma separated values for the "photo_size" parameter in the config file, and expand out that value into multiple "--size" arguments.

**Comment by boredazfcuk** [comment]
I've pushed a new version to Dockerhub which adds this new functionality. Details are in the CONFIGURATION.MD file or can be viewed by running `sync-icloud --help` but basically you prob just want `photo_size=original,adjusted`

**Comment by jmalexan** [comment]
This is most of it, although I believe you missed one of the supported sizes "alternative", used for RAW versions of photos when they are presented in the Photos app as "RAW + JPG".  It's in a "See Also" box at the very bottom of the page I linked.  If you add that to the argument checking, I think everything should be set.

**Comment by boredazfcuk** [comment]
Done

**Comment by jmalexan** [comment]
One more thing, looks like there's a bug at https://github.com/boredazfcuk/docker-icloudpd/blob/d13becb892bbee2b6e765ae458dddcab27001578/sync-icloud.sh#L1771 where the "alternative" check is checking against "photo_size" the array var, not "size" the current value in the for loop.  As is, I was getting "WARNING  Photo size alternative not recognised, disregarding" because original,adjusted,alternative !== alternative.  Fixing that gets everything working on my machine though.

**Comment by boredazfcuk** [comment]
Sorry, was in rush last night coz the footy was on. Just fixed it.
