### ISSUE TITLE
Synology_ Error during download - Exit code: 1

### ISSUE THREAD

**Issue by garytxd** [boredazfcuk/docker-icloudpd#75]
The first time to use icloudpd, can successful log in with Apple ID and can detected the files...
But after that, meets OSError(22, 'Invalid argument')

Detail:
1-07-10 09:18:26	stdout	2021-07-10 17:18:26 INFO     Next synchronisation at 05:18
2021-07-10 09:18:26	stdout	2021-07-10 17:18:26 INFO     iCloud login counter = 2
2021-07-10 09:18:26	stdout	2021-07-10 17:18:26 INFO     Days remaining until expiration: 89
2021-07-10 09:18:26	stdout	2021-07-10 17:18:26 INFO     Two factor authentication cookie expires: 2021-10-08 @ 08:50:53
2021-07-10 09:18:26	stdout	2021-07-10 17:18:26 INFO     Web cookie expires: 2021-09-08 @ 08:50:37
2021-07-10 09:18:26	stdout	2021-07-10 17:18:26 ERROR    Error during download - Exit code: 1
2021-07-10 09:18:26	stdout	requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-10 09:18:26	stdout	    raise ConnectionError(err, request=request)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
2021-07-10 09:18:26	stdout	    r = adapter.send(request, **kwargs)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
2021-07-10 09:18:26	stdout	    resp = self.send(prep, **send_kwargs)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
2021-07-10 09:18:26	stdout	    response = super(PyiCloudSession, self).request(*args, **kwargs)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
2021-07-10 09:18:26	stdout	    return self.request('POST', url, data=data, json=json, **kwargs)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
2021-07-10 09:18:26	stdout	    req = self.session.post(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
2021-07-10 09:18:26	stdout	    self.authenticate()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
2021-07-10 09:18:26	stdout	    icloud = pyicloud_ipd.PyiCloudService(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
2021-07-10 09:18:26	stdout	    icloud = authenticate(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
2021-07-10 09:18:26	stdout	    return callback(*args, **kwargs)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
2021-07-10 09:18:26	stdout	    return ctx.invoke(self.callback, **ctx.params)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
2021-07-10 09:18:26	stdout	    rv = self.invoke(ctx)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
2021-07-10 09:18:26	stdout	    return self.main(*args, **kwargs)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
2021-07-10 09:18:26	stdout	    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
2021-07-10 09:18:26	stdout	  File "/usr/bin/icloudpd", line 33, in <module>
2021-07-10 09:18:26	stdout	Traceback (most recent call last):
2021-07-10 09:18:26	stdout	
2021-07-10 09:18:26	stdout	During handling of the above exception, another exception occurred:
2021-07-10 09:18:26	stdout	
2021-07-10 09:18:26	stdout	urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-10 09:18:26	stdout	    self._sslobj.do_handshake()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
2021-07-10 09:18:26	stdout	    self.do_handshake()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
2021-07-10 09:18:26	stdout	    return self.sslsocket_class._create(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
2021-07-10 09:18:26	stdout	    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
2021-07-10 09:18:26	stdout	    ssl_sock = _ssl_wrap_socket_impl(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
2021-07-10 09:18:26	stdout	    self.sock = ssl_wrap_socket(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
2021-07-10 09:18:26	stdout	    conn.connect()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
2021-07-10 09:18:26	stdout	    self._validate_conn(conn)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
2021-07-10 09:18:26	stdout	    httplib_response = self._make_request(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2021-07-10 09:18:26	stdout	    raise value.with_traceback(tb)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
2021-07-10 09:18:26	stdout	    raise six.reraise(type(error), error, _stacktrace)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
2021-07-10 09:18:26	stdout	    retries = retries.increment(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
2021-07-10 09:18:26	stdout	    resp = conn.urlopen(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
2021-07-10 09:18:26	stdout	Traceback (most recent call last):
2021-07-10 09:18:26	stdout	
2021-07-10 09:18:26	stdout	During handling of the above exception, another exception occurred:
2021-07-10 09:18:26	stdout	
2021-07-10 09:18:26	stdout	OSError: [Errno 22] Invalid argument
2021-07-10 09:18:26	stdout	    self._sslobj.do_handshake()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
2021-07-10 09:18:26	stdout	    self.do_handshake()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
2021-07-10 09:18:26	stdout	    return self.sslsocket_class._create(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
2021-07-10 09:18:26	stdout	    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
2021-07-10 09:18:26	stdout	    ssl_sock = _ssl_wrap_socket_impl(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
2021-07-10 09:18:26	stdout	    self.sock = ssl_wrap_socket(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
2021-07-10 09:18:26	stdout	    conn.connect()
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
2021-07-10 09:18:26	stdout	    self._validate_conn(conn)
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
2021-07-10 09:18:26	stdout	    httplib_response = self._make_request(
2021-07-10 09:18:26	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2021-07-10 09:18:26	stdout	Traceback (most recent call last):
2021-07-10 09:18:26	stdout	2021-07-10 17:18:26 DEBUG    Authenticating...

Have no idea about this issue, and call help here
Thanks in advance for your help!

**Comment by boredazfcuk** [comment]
Can you look in the log file for a line that starts like:
```
2021-07-10 12:00:00 INFO     iCloudPD launch command:  /usr/bin/icloudpd --directory xxxxxxx
```

**Comment by garytxd** [comment]
2021-07-10 17:18:25 INFO     iCloudPD launch command: /usr/bin/icloudpd --directory /volume1/homes/gary_txd/Photos/iCloud --cookie-directory /config --folder-structure {:%Y/%m/%d} --username gary_txd@gmail.com  2>&1


checked the line
Seems no special character in my mail address and user name

**Comment by boredazfcuk** [comment]
Hmmm. Looks fine to me.

Can you remove your container and then re-create it, and post the full log please?

Aloso, you're best off removing your e-mail address from the logs, as bots scrape the internet looking for e-mail addresses all day long. Posting your address on a website is a sure fire way to get yourself added to junk-mail lists and garbage like that.

**Comment by garytxd** [comment]
Thank you for help me edited the personal info. 
Attached 2 logs for your reference, 1 from synology and 1 from terminal 
CAN NOT upload the file for unknown issue, so paste logs here

synology Log

2021-07-10 12:06:44	stdout	2021-07-10 20:06:44 INFO     Next synchronisation at 08:06
2021-07-10 12:06:44	stdout	2021-07-10 20:06:44 INFO     iCloud login counter = 1
2021-07-10 12:06:44	stdout	2021-07-10 20:06:44 INFO     Days remaining until expiration: 89
2021-07-10 12:06:44	stdout	2021-07-10 20:06:44 INFO     Two factor authentication cookie expires: 2021-10-08 @ 08:50:53
2021-07-10 12:06:44	stdout	2021-07-10 20:06:44 INFO     Web cookie expires: 2021-09-08 @ 08:50:37
2021-07-10 12:06:44	stdout	2021-07-10 20:06:44 ERROR    Check failed - Exit code: 1
2021-07-10 12:06:44	stdout	requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-10 12:06:44	stdout	    raise ConnectionError(err, request=request)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
2021-07-10 12:06:44	stdout	    r = adapter.send(request, **kwargs)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
2021-07-10 12:06:44	stdout	    resp = self.send(prep, **send_kwargs)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
2021-07-10 12:06:44	stdout	    response = super(PyiCloudSession, self).request(*args, **kwargs)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
2021-07-10 12:06:44	stdout	    return self.request('POST', url, data=data, json=json, **kwargs)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
2021-07-10 12:06:44	stdout	    request = self.session.post(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 157, in __init__
2021-07-10 12:06:44	stdout	    self._photos = PhotosService(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 329, in photos
2021-07-10 12:06:44	stdout	    photos = icloud.photos.albums[album]
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 281, in main
2021-07-10 12:06:44	stdout	    return callback(*args, **kwargs)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
2021-07-10 12:06:44	stdout	    return ctx.invoke(self.callback, **ctx.params)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
2021-07-10 12:06:44	stdout	    rv = self.invoke(ctx)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
2021-07-10 12:06:44	stdout	    return self.main(*args, **kwargs)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
2021-07-10 12:06:44	stdout	    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
2021-07-10 12:06:44	stdout	  File "/usr/bin/icloudpd", line 33, in <module>
2021-07-10 12:06:44	stdout	Traceback (most recent call last):
2021-07-10 12:06:44	stdout	
2021-07-10 12:06:44	stdout	During handling of the above exception, another exception occurred:
2021-07-10 12:06:44	stdout	
2021-07-10 12:06:44	stdout	urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-10 12:06:44	stdout	    self._sslobj.do_handshake()
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
2021-07-10 12:06:44	stdout	    self.do_handshake()
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
2021-07-10 12:06:44	stdout	    return self.sslsocket_class._create(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
2021-07-10 12:06:44	stdout	    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
2021-07-10 12:06:44	stdout	    ssl_sock = _ssl_wrap_socket_impl(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
2021-07-10 12:06:44	stdout	    self.sock = ssl_wrap_socket(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
2021-07-10 12:06:44	stdout	    conn.connect()
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
2021-07-10 12:06:44	stdout	    self._validate_conn(conn)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
2021-07-10 12:06:44	stdout	    httplib_response = self._make_request(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2021-07-10 12:06:44	stdout	    raise value.with_traceback(tb)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
2021-07-10 12:06:44	stdout	    raise six.reraise(type(error), error, _stacktrace)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
2021-07-10 12:06:44	stdout	    retries = retries.increment(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
2021-07-10 12:06:44	stdout	    resp = conn.urlopen(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
2021-07-10 12:06:44	stdout	Traceback (most recent call last):
2021-07-10 12:06:44	stdout	
2021-07-10 12:06:44	stdout	During handling of the above exception, another exception occurred:
2021-07-10 12:06:44	stdout	
2021-07-10 12:06:44	stdout	OSError: [Errno 22] Invalid argument
2021-07-10 12:06:44	stdout	    self._sslobj.do_handshake()
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
2021-07-10 12:06:44	stdout	    self.do_handshake()
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
2021-07-10 12:06:44	stdout	    return self.sslsocket_class._create(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
2021-07-10 12:06:44	stdout	    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
2021-07-10 12:06:44	stdout	    ssl_sock = _ssl_wrap_socket_impl(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
2021-07-10 12:06:44	stdout	    self.sock = ssl_wrap_socket(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
2021-07-10 12:06:44	stdout	    conn.connect()
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
2021-07-10 12:06:44	stdout	    self._validate_conn(conn)
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
2021-07-10 12:06:44	stdout	    httplib_response = self._make_request(
2021-07-10 12:06:44	stdout	  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2021-07-10 12:06:44	stdout	Traceback (most recent call last):
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Check for new files using password stored in keyring file...
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Failsafe file /volume1/homes/*******/Photos/iCloud/.mounted exists
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Check download directory mounted correctly
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Valid two factor authentication cookie found. Days until expiration: 89
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Cookie exists, check expiry date
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Check 2FA Cookie
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Sync user ******
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Command line options: --directory /volume1/homes/******/Photos/iCloud --cookie-directory /config --folder-structure {:%Y/%m} --username ******@hotmail.com
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Set 640 permissions on iCloud files, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Set 750 permissions on iCloud directories, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct group on keyring directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct owner on keyring directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct group on config directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct owner on config directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct group on icloudpd temp directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct owner on icloudpd temp directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Set group, users, on iCloud directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Set owner, ******, on iCloud directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Failsafe file /volume1/homes/******/Photos/iCloud/.mounted exists
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Check download directory mounted correctly
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct group on config directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Correct owner on config directory, if required
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     User, ******:1026, already created
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Group, users:100, already created
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Convert HEIC to JPEG: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Skip videos: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Live photo size: original
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Number of most recently added photos to download: Download All Photos
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Skip live photos: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Skip download check: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Photo size: original
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Auto delete: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Set EXIF date/time: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Time zone: Asia/Shanghai
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Synchronisation delay (minutes): 0
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Synchronisation interval: 43200
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     File permissions: 640
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Directory permissions: 750
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Folder structure: {:%Y/%m}
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Download destination directory: /volume1/homes/******/Photos/iCloud
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Cookie expiry notification period: 7
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Cookie path: /config/******hotmailcom
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Authentication Type: 2FA
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Apple ID password: usekeyring
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Apple ID: ******@hotmail.com
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     LAN IP Address: 172.17.0.2
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Force GID: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Local group: users:100
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Local user: ******:1026
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Command line option --Generate2FACookie specified
2021-07-10 12:06:40	stdout	2021-07-10 20:06:40 INFO     Interactive session: False
2021-07-10 12:06:40	stdout	2021-07-10 20:06:39 INFO     pyicloud-ipd version: 0.10.1
2021-07-10 12:06:39	stdout	2021-07-10 20:06:38 INFO     icloudpd version: 1.7.2
2021-07-10 12:06:38	stdout	2021-07-10 20:06:38 INFO     Python version: 3.8.10
2021-07-10 12:06:38	stdout	2021-07-10 20:06:38 INFO     Alpine Linux 3.13.5
2021-07-10 12:06:38	stdout	2021-07-10 20:06:38 INFO     ***** /usr/local/bin/sync-icloud.sh hash: efa1b0c1766794123dbbd1387b1e59ff *****
2021-07-10 12:06:38	stdout	2021-07-10 20:06:38 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/07/05_23:22 *****
2021-07-10 12:06:38	stdout	2021-07-10 20:06:38 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****


Terminal Log

root@DS220plus:~# docker create \
>    --name iCloud-*****1 \
>    --hostname iCloudDownloader \
>    --network bridge \
>    --restart=always \
>    --env user=***** \
>    --env user_id=1026 \
>    --env group=users \
>    --env group_id=100 \
>    --env apple_id=******@hotmail.com \
>    --env apple_password=usekeyring \
>    --env authentication_type=2FA \
>    --env synchronisation_interval=43200 \
>    --env TZ=Asia/Shanghai \
>    --env download_path=/volume1/homes/******/Photos/iCloud \
>    --env folder_structure={:%Y/%m} \
>    --volume /volume1/docker/icloudpd/icloudconfig:/config \
>    --volume /volume1/homes/******/Photos/iCloud:/volume1/homes/******/Photos/iCloud \
>    boredazfcuk/icloudpd
f3e400cbf0a86a2be2691455d379c1a7babdb07e2f709aacbcd6ad20470043fc
root@DS220plus:~# docker container ls
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                             PORTS     NAMES
f3e400cbf0a8   boredazfcuk/icloudpd   "/bin/sh -c /usr/loc…"   24 seconds ago   Up 17 seconds (health: starting)             iCloud-******-1
root@DS220plus:~# 
root@DS220plus:~# 
root@DS220plus:~# docker exec -it f3e400cbf0a8 /usr/local/bin/sync-icloud.sh

2021-07-10 16:50:33 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-07-10 16:50:33 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/07/05_23:22 *****
2021-07-10 16:50:33 INFO     ***** /usr/local/bin/sync-icloud.sh hash: efa1b0c1766794123dbbd1387b1e59ff *****
2021-07-10 16:50:33 INFO     Alpine Linux 3.13.5
2021-07-10 16:50:33 INFO     Python version: 3.8.10
2021-07-10 16:50:33 INFO     icloudpd version: 1.7.2
2021-07-10 16:50:34 INFO     pyicloud-ipd version: 0.10.1
2021-07-10 16:50:35 INFO     Terminal type: xterm
2021-07-10 16:50:35 INFO     Interactive session: True
2021-07-10 16:50:35 INFO     Command line option --Generate2FACookie specified
2021-07-10 16:50:35 INFO     Local user: ******:1026
2021-07-10 16:50:35 INFO     Local group: users:100
2021-07-10 16:50:35 INFO     Force GID: False
2021-07-10 16:50:35 INFO     LAN IP Address: 172.17.0.2
2021-07-10 16:50:35 INFO     Apple ID: ******@hotmail.com
2021-07-10 16:50:35 INFO     Apple ID password: usekeyring
2021-07-10 16:50:35 INFO     Authentication Type: 2FA
2021-07-10 16:50:35 INFO     Cookie path: /config/******hotmailcom
2021-07-10 16:50:35 INFO     Cookie expiry notification period: 7
2021-07-10 16:50:35 INFO     Download destination directory: /volume1/homes/******/Photos/iCloud
2021-07-10 16:50:35 INFO     Folder structure: {:%Y/%m}
2021-07-10 16:50:35 INFO     Directory permissions: 750
2021-07-10 16:50:35 INFO     File permissions: 640
2021-07-10 16:50:35 INFO     Synchronisation interval: 43200
2021-07-10 16:50:35 INFO     Synchronisation delay (minutes): 0
2021-07-10 16:50:35 INFO     Time zone: Asia/Shanghai
2021-07-10 16:50:35 INFO     Set EXIF date/time: False
2021-07-10 16:50:35 INFO     Auto delete: False
2021-07-10 16:50:35 INFO     Photo size: original
2021-07-10 16:50:35 INFO     Skip download check: False
2021-07-10 16:50:35 INFO     Skip live photos: False
2021-07-10 16:50:35 INFO     Number of most recently added photos to download: Download All Photos
2021-07-10 16:50:35 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-07-10 16:50:35 INFO     Live photo size: original
2021-07-10 16:50:35 INFO     Skip videos: False
2021-07-10 16:50:35 INFO     Convert HEIC to JPEG: False
2021-07-10 16:50:35 INFO     Group, users:100, already created
2021-07-10 16:50:35 INFO     User, ******:1026, already created
2021-07-10 16:50:35 INFO     Correct owner on config directory, if required
2021-07-10 16:50:35 INFO     Correct group on config directory, if required
2021-07-10 16:50:35 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2021-07-10 16:50:35 INFO     Correct owner on config directory, if required
2021-07-10 16:50:35 INFO     Correct group on config directory, if required
2021-07-10 16:50:35 INFO     Generate 2FA cookie with password: usekeyring
2021-07-10 16:50:35 INFO     Check for new files using password stored in keyring file.
  0: SMS to *********90
  1: SMS to *********29
  2: Enter two-factor authentication code
Please choose an option: [0]: 0
Please enter two-factor authentication code: 122009
2021-07-10 16:50:57 INFO     Two factor authentication cookie generated. Sync should now be successful.
root@DS220plus:~# docker container ls
CONTAINER ID   IMAGE                  COMMAND                  CREATED             STATUS                             PORTS     NAMES
f3e400cbf0a8   boredazfcuk/icloudpd   "/bin/sh -c /usr/loc…"   5 minutes ago       Up 5 minutes (unhealthy)                     iCloud-******-1
42a26efd517a   boredazfcuk/icloudpd   "/bin/sh -c /usr/loc…"   About an hour ago   Up 11 seconds (health: starting)             iCloud-******
root@DS220plus:~# 
root@DS220plus:~# 
root@DS220plus:~# docker exec -it 42a26efd517a /usr/local/bin/sync-icloud.sh

2021-07-10 16:55:27 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-07-10 16:55:27 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/07/05_23:22 *****
2021-07-10 16:55:27 INFO     ***** /usr/local/bin/sync-icloud.sh hash: efa1b0c1766794123dbbd1387b1e59ff *****
2021-07-10 16:55:27 INFO     Alpine Linux 3.13.5
2021-07-10 16:55:27 INFO     Python version: 3.8.10
2021-07-10 16:55:27 INFO     icloudpd version: 1.7.2
2021-07-10 16:55:28 INFO     pyicloud-ipd version: 0.10.1
2021-07-10 16:55:29 INFO     Terminal type: xterm
2021-07-10 16:55:29 INFO     Interactive session: True
2021-07-10 16:55:29 INFO     Command line option --Generate2FACookie specified
2021-07-10 16:55:29 INFO     Local user: ******:1026
2021-07-10 16:55:29 INFO     Local group: users:100
2021-07-10 16:55:29 INFO     Force GID: False
2021-07-10 16:55:29 INFO     LAN IP Address: 172.17.0.3
2021-07-10 16:55:29 INFO     Apple ID: ******@hotmail.com
2021-07-10 16:55:29 INFO     Apple ID password: usekeyring
2021-07-10 16:55:29 INFO     Authentication Type: 2FA
2021-07-10 16:55:29 INFO     Cookie path: /config/******hotmailcom
2021-07-10 16:55:29 INFO     Cookie expiry notification period: 7
2021-07-10 16:55:29 INFO     Download destination directory: /mnt/volume1/homes/******/Photos/iCloud
2021-07-10 16:55:29 INFO     Folder structure: {:%Y/%m}
2021-07-10 16:55:29 INFO     Directory permissions: 750
2021-07-10 16:55:29 INFO     File permissions: 640
2021-07-10 16:55:29 INFO     Synchronisation interval: 43200
2021-07-10 16:55:29 INFO     Synchronisation delay (minutes): 0
2021-07-10 16:55:29 INFO     Time zone: Asia/Shanghai
2021-07-10 16:55:29 INFO     Set EXIF date/time: False
2021-07-10 16:55:29 INFO     Auto delete: False
2021-07-10 16:55:29 INFO     Photo size: original
2021-07-10 16:55:29 INFO     Skip download check: False
2021-07-10 16:55:29 INFO     Skip live photos: False
2021-07-10 16:55:29 INFO     Number of most recently added photos to download: Download All Photos
2021-07-10 16:55:29 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-07-10 16:55:29 INFO     Live photo size: original
2021-07-10 16:55:29 INFO     Skip videos: False
2021-07-10 16:55:29 INFO     Convert HEIC to JPEG: False
2021-07-10 16:55:29 INFO     Group, users:100, already created
2021-07-10 16:55:29 INFO     User, ******:1026, already created
2021-07-10 16:55:29 INFO     Correct owner on config directory, if required
2021-07-10 16:55:29 INFO     Correct group on config directory, if required
2021-07-10 16:55:29 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2021-07-10 16:55:29 INFO     Correct owner on config directory, if required
2021-07-10 16:55:29 INFO     Correct group on config directory, if required
2021-07-10 16:55:29 INFO     Generate 2FA cookie with password: usekeyring
2021-07-10 16:55:29 INFO     Check for new files using password stored in keyring file.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-10 16:55:31 INFO     Two factor authentication cookie generated. Sync should now be successful.

**Comment by boredazfcuk** [comment]
Hi,

This bit is causing an issue:
```
2021-07-10 16:55:29 INFO Command line option --Generate2FACookie specified
```

The **command_line_options** variable is for passing command line options to the underlying icloudpd application which my script launches, and uses to download the photos. You've set it to **--Generate2FACookie** which is a command line parameter my script uses. Remove that error and it will fix this error:
```
2021-07-10 09:18:26 stdout requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
```

To generate the cookie, you need to pass that command line option to my script when you do this bit:
```
docker exec -it 42a26efd517a /usr/local/bin/sync-icloud.sh --Generate2FACookie
```

**Comment by bauzer714** [comment]
@boredazfcuk  If the person is on Synology, don't they need the interactive_only environment variable, and then execute the command mentioned?

**Comment by garytxd** [comment]
Great，issue solved, thank you...

**Comment by boredazfcuk** [comment]
> @boredazfcuk If the person is on Synology, don't they need the interactive_only environment variable, and then execute the command mentioned?

Yes, I'd like to get rid of that requirement by finding some way of detecting if the container is running on a Synology device, but I don't actually own one to mess about with... I don't think hardware information is actually passed to containers from the host anyway, so even if I did have one, I don't think it would result in much.


> 
> 
> Great，issue solved, thank you...

Awesome. Thanks for letting me know and closing the issue.

**Comment by boredazfcuk** [comment]
> @boredazfcuk If the person is on Synology, don't they need the interactive_only environment variable, and then execute the command mentioned?

Got bored. Implemented this tonight.

Script now defaults to downloading files, instead of configuring the password/cookie. There's no need for the **interactive_only** variable any more as the script assumes that everyone is running it interactively. This should make things easier for Synology/QNAP users as that variable is no longer needed, so they won't get stuck on the authentication screen when launching the container, it'll just throw an error if the system keyring and cookie files don't exist.

Everyone now has to use the --Initialise command line option to set the keyring password and create the cookie file, which has replaced --Generate2FACookie, as it more accurately describes the function now it also sets the password. I've also made the error message explain things a load better, so people should have a clue what's happened and how to fix it, if they start getting the new error after deleting/recreating their containers.

**Comment by toastsgithub** [comment]
Hi, I met similar problem, while I found no clue but "Invalid argument" in logs
could you please help me with it?

here are logs below, thanks in advance



------------------ logs ------------------
2021-07-24 21:14:16 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-07-24 21:14:16 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/07/20_03:45 *****
2021-07-24 21:14:16 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 142762f103ffb62457357e9998a0b40d *****
2021-07-24 21:14:16 INFO     Alpine Linux 3.13.5
2021-07-24 21:14:16 INFO     Python version: 3.8.10
2021-07-24 21:14:16 INFO     icloudpd version: 1.7.2
2021-07-24 21:14:20 INFO     pyicloud-ipd version: 0.10.1
2021-07-24 21:14:21 INFO     Local user: zmou:1000
2021-07-24 21:14:21 INFO     Local group: group:1000
2021-07-24 21:14:21 INFO     Force GID: False
2021-07-24 21:14:21 INFO     LAN IP Address: 172.17.0.2
2021-07-24 21:14:21 INFO     Apple ID: **@qq.com
2021-07-24 21:14:21 INFO     Authentication Type: 2FA
2021-07-24 21:14:21 INFO     Cookie path: /config/**qqcom
2021-07-24 21:14:21 INFO     Cookie expiry notification period: 7
2021-07-24 21:14:21 INFO     Download destination directory: /home/zmou/iCloud
2021-07-24 21:14:21 INFO     Folder structure: {:%Y/%m/%d}
2021-07-24 21:14:21 INFO     Directory permissions: 750
2021-07-24 21:14:21 INFO     File permissions: 640
2021-07-24 21:14:21 INFO     Synchronisation interval: 86400
2021-07-24 21:14:21 INFO     Synchronisation delay (minutes): 0
2021-07-24 21:14:21 INFO     Time zone: Asia/Shanghai
2021-07-24 21:14:21 INFO     Set EXIF date/time: False
2021-07-24 21:14:21 INFO     Auto delete: False
2021-07-24 21:14:21 INFO     Photo size: original
2021-07-24 21:14:21 INFO     Skip download check: False
2021-07-24 21:14:21 INFO     Skip live photos: False
2021-07-24 21:14:21 INFO     Number of most recently added photos to download: Download All Photos
2021-07-24 21:14:21 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-07-24 21:14:21 INFO     Live photo size: original
2021-07-24 21:14:21 INFO     Skip videos: False
2021-07-24 21:14:21 INFO     Convert HEIC to JPEG: False
2021-07-24 21:14:21 INFO     Group, group:1000, already created
2021-07-24 21:14:21 INFO     User, zmou:1000, already created
2021-07-24 21:14:21 INFO     Correct owner on config directory, if required
2021-07-24 21:14:21 INFO     Correct group on config directory, if required
2021-07-24 21:14:21 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2021-07-24 21:14:21 INFO     Check download directory mounted correctly
2021-07-24 21:14:21 INFO     Failsafe file /home/zmou/iCloud/.mounted exists
2021-07-24 21:14:21 INFO     Set owner, zmou, on iCloud directory, if required
2021-07-24 21:14:21 INFO     Set group, group, on iCloud directory, if required
2021-07-24 21:14:21 INFO     Correct owner on icloudpd temp directory, if required
2021-07-24 21:14:21 INFO     Correct group on icloudpd temp directory, if required
2021-07-24 21:14:21 INFO     Correct owner on config directory, if required
2021-07-24 21:14:22 INFO     Correct group on config directory, if required
2021-07-24 21:14:22 INFO     Correct owner on keyring directory, if required
2021-07-24 21:14:22 INFO     Correct group on keyring directory, if required
2021-07-24 21:14:22 INFO     Set 750 permissions on iCloud directories, if required
2021-07-24 21:14:22 INFO     Set 640 permissions on iCloud files, if required
2021-07-24 21:14:22 INFO     Sync user zmou
2021-07-24 21:14:22 INFO     Check 2FA Cookie
2021-07-24 21:14:22 INFO     Cookie exists, check expiry date
2021-07-24 21:14:22 INFO     Valid two factor authentication cookie found. Days until expiration: 89
2021-07-24 21:14:22 INFO     Check download directory mounted correctly
2021-07-24 21:14:22 INFO     Failsafe file /home/zmou/iCloud/.mounted exists
2021-07-24 21:14:22 INFO     Check for new files using password stored in keyring file...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-24 21:14:23 ERROR    Check failed - Exit code: 1
2021-07-24 21:14:23 INFO     Web cookie expires: 2021-09-22 @ 08:50:39
2021-07-24 21:14:23 INFO     Two factor authentication cookie expires: 2021-10-22 @ 08:50:59
2021-07-24 21:14:23 INFO     Days remaining until expiration: 89
2021-07-24 21:14:23 INFO     iCloud login counter = 1
2021-07-24 21:14:23 INFO     Next synchronisation at 21:14

**Comment by boredazfcuk** [comment]
> Hi, I met similar problem, while I found no clue but "Invalid argument" in logs
> could you please help me with it?
> 
> here are logs below, thanks in advance

The problem was due to OP launching the container with an invalid command line option.

I've just pushed a new image to DockerHub which sanitises the command line options. It also upgrades a few of the Python packages included in the image. I noticed a fair few modules had been upgraded recently, it may be that you've found a bug that one of them fixes.

Please upgrade and post logs again if problem persists.

Thanks.

**Comment by toastsgithub** [comment]
Hi, thanks for your immediate reply, I just upgrate the docker image as you describe
but the problem is still there, and I think I didn't use any special options or environment variables



------------------------ LOG ------------------------
2021-07-24 15:23:51 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-07-24 15:23:51 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/07/24_14:58 *****
2021-07-24 15:23:51 INFO     ***** /usr/local/bin/sync-icloud.sh hash: f12dfc75f05bde63a13f1291b8b454e5 *****
2021-07-24 15:23:51 INFO     Alpine Linux 3.13.5
2021-07-24 15:23:51 INFO     Python version: 3.8.10
2021-07-24 15:23:51 INFO     icloudpd version: 1.7.2
2021-07-24 15:24:00 INFO     pyicloud-ipd version: 0.10.1
2021-07-24 15:24:01 INFO     Local user: zmou:1000
2021-07-24 15:24:01 INFO     Local group: group:1000
2021-07-24 15:24:01 INFO     Force GID: False
2021-07-24 15:24:01 INFO     LAN IP Address: 172.17.0.2
2021-07-24 15:24:01 INFO     Apple ID: **@qq.com
2021-07-24 15:24:01 INFO     Authentication Type: 2FA
2021-07-24 15:24:01 INFO     Cookie path: /config/**qqcom
2021-07-24 15:24:01 INFO     Cookie expiry notification period: 7
2021-07-24 15:24:01 INFO     Download destination directory: /home/zmou/iCloud
2021-07-24 15:24:01 INFO     Folder structure: {:%Y/%m/%d}
2021-07-24 15:24:01 INFO     Directory permissions: 750
2021-07-24 15:24:01 INFO     File permissions: 640
2021-07-24 15:24:01 INFO     Synchronisation interval: 86400
2021-07-24 15:24:01 INFO     Synchronisation delay (minutes): 0
2021-07-24 15:24:01 INFO     Time zone: UTC
2021-07-24 15:24:01 INFO     Set EXIF date/time: False
2021-07-24 15:24:01 INFO     Auto delete: False
2021-07-24 15:24:01 INFO     Photo size: original
2021-07-24 15:24:01 INFO     Skip download check: False
2021-07-24 15:24:01 INFO     Skip live photos: False
2021-07-24 15:24:01 INFO     Number of most recently added photos to download: Download All Photos
2021-07-24 15:24:01 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-07-24 15:24:01 INFO     Live photo size: original
2021-07-24 15:24:01 INFO     Skip videos: False
2021-07-24 15:24:01 INFO     Convert HEIC to JPEG: False
2021-07-24 15:24:01 INFO     Creating group group:1000
2021-07-24 15:24:01 INFO     Creating user zmou:1000
2021-07-24 15:24:01 INFO     Correct owner on config directory, if required
2021-07-24 15:24:01 INFO     Correct group on config directory, if required
2021-07-24 15:24:01 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2021-07-24 15:24:01 INFO     Check download directory mounted correctly
2021-07-24 15:24:01 INFO     Failsafe file /home/zmou/iCloud/.mounted exists
2021-07-24 15:24:01 INFO     Set owner, zmou, on iCloud directory, if required
2021-07-24 15:24:02 INFO     Set group, group, on iCloud directory, if required
2021-07-24 15:24:02 INFO     Correct owner on icloudpd temp directory, if required
2021-07-24 15:24:02 INFO     Correct group on icloudpd temp directory, if required
2021-07-24 15:24:02 INFO     Correct owner on config directory, if required
2021-07-24 15:24:02 INFO     Correct group on config directory, if required
2021-07-24 15:24:02 INFO     Correct owner on keyring directory, if required
2021-07-24 15:24:02 INFO     Correct group on keyring directory, if required
2021-07-24 15:24:02 INFO     Set 750 permissions on iCloud directories, if required
2021-07-24 15:24:02 INFO     Set 640 permissions on iCloud files, if required
2021-07-24 15:24:02 INFO     Sync user zmou
2021-07-24 15:24:02 INFO     Check 2FA Cookie
2021-07-24 15:24:02 INFO     Cookie exists, check expiry date
2021-07-24 15:24:02 INFO     Valid two factor authentication cookie found. Days until expiration: 89
2021-07-24 15:24:02 INFO     Check download directory mounted correctly
2021-07-24 15:24:02 INFO     Failsafe file /home/zmou/iCloud/.mounted exists
2021-07-24 15:24:02 INFO     Check for new files using password stored in keyring file...

(...after scan some file)
/home/zmou/iCloud/2016/07/14/IMG_1229.JPG
/home/zmou/iCloud/2016/07/13/IMG_1228.JPG
/home/zmou/iCloud/2016/07/13/IMG_1226.JPG
/home/zmou/iCloud/2016/07/13/IMG_1225.JPG
/home/zmou/iCloud/2016/07/12/IMG_1224.JPG
/home/zmou/iCloud/2016/07/13/IMG_1223.JPG
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 561, in main
    item = next(photos_iterator)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
    request = self.photos_request(offset)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
    return self.service.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
2021-07-24 15:32:27 ERROR    Check failed - Exit code: 1
2021-07-24 15:32:27 INFO     Web cookie expires: 2021-09-22 @ 08:50:39
2021-07-24 15:32:27 INFO     Two factor authentication cookie expires: 2021-10-22 @ 08:50:59
2021-07-24 15:32:27 INFO     Days remaining until expiration: 89
2021-07-24 15:32:27 INFO     iCloud login counter = 1
2021-07-24 15:32:27 INFO     Next synchronisation at 15:32

**Comment by boredazfcuk** [comment]
I'm not sure what could be causing this and cannot replicate it...

The only thing I can thing is that there is a filename on your iCloud storage that the downloading app can't handle. Can you check on iCloud.com to see if there's any non-standard filenames?

**Comment by toastsgithub** [comment]
Hi, after trying many different approachs
I finally found checking「run with high privilege」can solve this problem (I run this container on my synology NAS）
I dont know the deeply root cause, but it works anyway (I guess it's due to write permission on docker container or something like that)

**Comment by boredazfcuk** [comment]
Odd. I do not run the container in privileged mode and do not see this error. I also have a number of people who use this on Synology devices and nobody has mentioned this before. I'm not sure why it's just you receiving this and not others.

How are you creating your container? Are you definitely mapping the two volumes correctly by specifying the locations?

e.g. buy adding the volume parameter if creating from the command line...:
```
    --volume /volume1/docker/icloudpd/icloudconfig:/config
    --volume /volume1/homes/user/Photos/iCloud:/volume1/homes/user/Photos/iCloud
```
...or from a docker-compose.yaml like this:
```
volumes:
   config:
      name: icloudpd_config

services:
   icloudpd:
      volumes:
         - config:/config
         - ./iCloud/:/home/${user}/iCloud/
...
```
